# version: "3"

# 构建时临时使用代理的方法
# fq_host=the_ip_address_of_host:7890
# 以下二选一
# docker compose build --build-arg HTTP_PROXY=http://$fq_host --build-arg HTTPS_PROXY=http://$fq_host  --build-arg ALL_PROXY=socks5://$fq_host --no-cache
# 或者
# docker compose build --build-arg ALL_PROXY=socks5://$fq_host --no-cache

# official repo URL=https://github.com/qbittorrent/docker-qbittorrent-nox
services:
  qbittorrent_nox:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: ./default_official.env
        required: true # default
      - path: /media/justsave/docker/env/qbittorrent_nox/docker.env
        required: false
    container_name: qbittorrent-nox
    # image: qbittorrentofficial/qbittorrent-nox:4.6.5-1
    image: qbittorrent-nox-xfl:4.6.4
    pull_policy: build
    build:
      context: ./
      dockerfile: qbittorrent-nox.Dockerfile
      # args:
      #   - ALL_PROXY=socks5://host.docker.internal:7890
      # extra_hosts:
      #   - "host.docker.internal:host-gateway"
    # for debugging
    cap_add:
      - SYS_PTRACE
    # read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      # 数据持久化
      - /media/justsave/docker/volume/qbittorrent_nox/downloads:/downloads
      - /media/justsave/docker/volume/qbittorrent_nox/official/config:/config
      # - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config/.cache:/config/.cache
      # - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config/qBittorrent/BT_backup:/config/qBittorrent/data/BT_backup
      # - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config/qBittorrent/GeoDB:/config/qBittorrent/data/GeoDB
      # - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config/qBittorrent/data/logs:/config/qBittorrent/data/logs
      # - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config/qBittorrent/rss:/config/qBittorrent/config/rss
      # - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config/qBittorrent/rss/articles:/config/qBittorrent/data/rss/articles
      - /media/justsave/BT:/media/justsave/BT
      - /media/justsave/PT:/media/justsave/PT
    # restart: always
    # restart: "no"
    restart: unless-stopped
