# version: "3"

# official repo URL=https://github.com/linuxserver/docker-qbittorrent
services:
  qbittorrent_nox:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/qbittorrent_nox/docker.env
        required: false
    container_name: qbittorrent-nox
    image: linuxserver/qbittorrent:latest
    pull_policy: always
    # for debugging
    cap_add:
      - SYS_PTRACE
    environment:
      - PUID=2005
      - PGID=1999
      - WEBUI_PORT=28012
    # read_only: true
    stop_grace_period: 30m
    # tmpfs:
    #   - /tmp
    tty: true
    volumes:
      # 数据持久化
      - /media/justsave/docker/volume/qbittorrent_nox:/media/justsave/docker/volume/qbittorrent_nox
      - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config:/config
      - /media/justsave/docker/volume/qbittorrent_nox/downloads:/downloads
      - /media/justsave/BT:/media/justsave/BT
      - /media/justsave/PT:/media/justsave/PT
    # restart: always
    # restart: "no"
    restart: unless-stopped
