# version: "3"

# 构建时临时使用代理的方法
# fq_host=the_ip_address_of_host:7890
# 以下二选一
# docker compose build --build-arg HTTP_PROXY=http://$fq_host --build-arg HTTPS_PROXY=http://$fq_host  --build-arg ALL_PROXY=socks5://$fq_host --no-cache
# 或者
# docker compose build --build-arg ALL_PROXY=socks5://$fq_host --no-cache

# official repo URL=https://github.com/qbittorrent/docker-qbittorrent-nox
services:
  qbittorrent_nox:
    container_name: qbittorrent-nox
    # image: qbittorrentofficial/qbittorrent-nox:4.6.5-1
    image: qbittorrent-nox-xfl:4.6.4
    pull_policy: build
    build:
      context: ./
      dockerfile: qbittorrent-nox.Dockerfile
      # args:
      #   - ALL_PROXY=socks5://host.docker.internal:7890
      # extra_hosts:
      #   - "host.docker.internal:host-gateway"
    # for debugging
    cap_add:
      - SYS_PTRACE
    environment:
      #- PAGID=10000
      - PUID=2005
      - PGID=1999
      - QBT_EULA=accept
      - QBT_VERSION=4.6.4
      - QBT_WEBUI_PORT=28012
    # read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # 数据持久化
      - /media/justsave/docker/volume/qbittorrent_nox/config:/config
      - /media/justsave/docker/volume/qbittorrent_nox/downloads:/downloads
      - /media/justsave/BT:/media/justsave/BT
      - /media/justsave/PT:/media/justsave/PT
      # 挂载 WebUI
      - /media/justsave/wwwroot/vuetorrent:/media/justsave/wwwroot/vuetorrent:ro
    network_mode: host
    # restart: always
    # restart: "no"
    restart: unless-stopped
