# version: "3"

# official repo URL=https://github.com/linuxserver/docker-qbittorrent
services:
  qbittorrent_nox:
    env_file:
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/qbittorrent_nox/docker.env
        required: false
    container_name: qbittorrent-nox
    image: linuxserver/qbittorrent:latest
    pull_policy: always
    # for debugging
    cap_add:
      - SYS_PTRACE
    environment:
      - PUID=2005
      - PGID=1999
      - WEBUI_PORT=28012
    # read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      # 数据持久化
      - /media/justsave/docker/volume/qbittorrent_nox:/media/justsave/docker/volume/qbittorrent_nox
      - /media/justsave/docker/volume/qbittorrent_nox/linuxserver/config:/config
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/BT_backup:/config/qBittorrent/BT_backup
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/GeoDB:/config/qBittorrent/GeoDB
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/logs:/config/qBittorrent/logs
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/config/rss:/config/qBittorrent/rss
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/articles:/config/qBittorrent/rss/articles
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/torrents.db:/config/qBittorrent/torrents.db
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/torrents.db-shm:/config/qBittorrent/torrents.db-shm
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/data/torrents.db-wal:/config/qBittorrent/torrents.db-wal
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/config/categories.json:/config/qBittorrent/categories.json
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/config/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/config/qBittorrent-data.conf:/config/qBittorrent/qBittorrent-data.conf
      - /media/justsave/docker/volume/qbittorrent_nox/official/config/qBittorrent/config/watched_folders.json:/config/qBittorrent/watched_folders.json
      - /media/justsave/docker/volume/qbittorrent_nox/downloads:/downloads
      - /media/justsave/BT:/media/justsave/BT
      - /media/justsave/PT:/media/justsave/PT
    network_mode: host
    # restart: always
    # restart: "no"
    restart: unless-stopped
