services:
  mosdns:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: mosdns
    logging:
      options:
        max-size: 4m
    # network_mode: bridge
    # ports:
    #   - "5553:5553"
    #   - "5553:5553/udp"
    network_mode: host
