# version: "3.8"

# official repo URL=https://github.com/tsl0922/ttyd
services:
  ttyd:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/ttyd/docker.env
        required: false
    container_name: ttyd
    # image: tsl0922/ttyd:alpine
    image: tsl0922/ttyd:alpine-xfl
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /media/justsave/docker/compose/build_resource
      dockerfile: ttyd-xfl.Dockerfile
    environment:
      - MY_DOCKER_APP_USER_NAME=ttyd
      - PUID=33 # id -u www-data 重装系统后可能需要自己创建一个 www-data 用户
      - PGID=33 # id -g www-data 重装系统后可能需要自己创建一个 www-data 用户组
    # command: "ttyd --writable --ipv6 --port 28041 bash"
    volumes:
      # 持久化
      - /media/justsave/docker/volume/ttyd/home:/home/ttyd
      # socket 通信
      - /var/run/ttyd:/var/run/ttyd
    # ports:
    #   - 28041:28041
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

# Nginx 
