services:
  netdata:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: netdata
    logging:
      options:
        max-size: 4m
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    network_mode: host
