# version: "3"
services:
  debian_test:
    container_name: debian-test
    image: debian:bookworm
    restart: "no"
    network_mode: bridge
    command: /bin/bash -c "touch /tmp/just_hold_docker_bash.txt && tail -f /tmp/just_hold_docker_bash.txt"

# 强行停机方法
# docker compose down --timeout 1
