services:
  hertzbeat:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: hertzbeat
    network_mode: bridge
    ports:
      - "127.0.0.1:28018:1157"
      - "127.0.0.1:1158:1158"
