services:
  jenkins:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: jenkins
    ports:
      - "127.0.0.1:28011:8080"
      - "127.0.0.1:28011:8080/udp"
      - "50000:50000"
      - "50000:50000/udp"
    network_mode: bridge
