# official repo URL=
services:
  docker_setup:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/docker_setup/docker.env
        required: false
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: docker-setup
    image: docker_setup
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /media/justsave/docker/compose/build_resource
      dockerfile: xfl.Dockerfile
      pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/justsave/docker/compose:/media/justsave/docker/compose
    restart: "no"
