# version: "3.5"

# official repo URL=https://github.com/PurpleI2P/i2pd
# official docs URL=https://i2pd.readthedocs.io/en/latest/
services:
  i2pd:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: i2pd
    # command: "--help"
    logging:
      options:
        max-size: 4m
    network_mode: host
