# version: "3.5"

# official repo URL=https://github.com/PurpleI2P/i2pd
# official docs URL=https://i2pd.readthedocs.io/en/latest/
services:
  i2pd:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: ./default.env
        required: true # default
      - path: /media/justsave/docker/env/i2pd/docker.env
        required: false
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "cc.xfl12345.code.share.docker.setup.localbuild=true"
    container_name: i2pd
    image: i2pd-xfl
    pull_policy: build
    build:
      context: ./
      additional_contexts:
        resources: /media/justsave/docker/compose/build_resource
      dockerfile: i2pd-xfl.Dockerfile
      pull: true
    volumes:
      - /media/justsave/docker/volume/i2pd/data:/home/i2pd/data  # Persist data
