networks:
  headscale-docker-bridge:
    name: "headscale-docker-bridge"
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.20.3.0/24"
          gateway: "172.20.3.1"
          ip_range: "172.20.3.0/24"
        - subnet: "fd00:dcdc:3::/64"
    driver_opts:
      com.docker.network.bridge.name: "br-headscale0"
