services:
  headscale:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: headscale
    ports:
      # - "8090:8090"
      - "127.0.0.1:28015:8080"
      - "0.0.0.0:9090:9090"
      - "3478:3478/udp"

  headscale_webui:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: headscale_webui
    ports:
      - "127.0.0.1:28016:5000"

  tailscale_client:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: tailscale_client
    network_mode: host

include:
  - ./docker-compose.network.yml
