services:
  headscale:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: headscale
  headscale_webui:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: headscale_webui
  tailscale_client:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: tailscale_client
    network_mode: host

include:
  - ./docker-compose.network.yml
