services:
  php_fpm:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: php_fpm
    logging:
      options:
        max-size: 4m
    network_mode: host
    volumes:
      # override the php-fpm default configuration
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
