# version: '3.1'

# official repo URL=https://github.com/phpmyadmin/docker
# official docs URL=https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-docker
services:
  phpmyadmin:
    env_file: /media/justsave/docker/env/phpmyadmin/docker.env
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      # - PMA_ARBITRARY=0
      - PMA_SOCKET=/var/run/mysqld/mysqld.sock
    volumes:
      # mysql unix socket
      - /var/run/mysqld:/var/run/mysqld
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - 28009:80
    restart: unless-stopped
