services:
  phpmyadmin:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: phpmyadmin
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - 127.0.0.1:28009:80
