services:
  redroid:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: redroid
    logging:
      options:
        max-size: 4m
    networks:
      my_redroid_network_bridge_host:
        ipv6_address: fd00:250:0:ffff::250
      my_redroid_network_macvlan:
        ipv4_address: 192.168.8.112
    ports:
      - 5555:5555

include:
  - ./docker-compose.network.yml
