services:
  clash:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: clash
    network_mode: host
  metacubexd:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: metacubexd
    ports:
      - 127.0.0.1:28002:80
    network_mode: bridge
