services:
  gitea:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: gitea
    network_mode: bridge
  gitea_runner:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: gitea_runner
    network_mode: bridge
