# version: "3"

# official docs URL=https://docs.gitea.com/installation/install-with-docker
services:
  gitea:
    env_file: /media/justsave/docker/env/gitea/docker.env
    image: gitea/gitea:1.22
    pull_policy: always
    container_name: gitea
    # UID: id -u gitea
    environment:
      - USER_UID=2009
      - USER_GID=2009
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # 持久化
      - /media/justsave/docker/volume/gitea/data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  gitea_runner:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: /media/justsave/docker/env/gitea/runner/docker.env
        required: false
    image: gitea/act_runner:latest
    pull_policy: always
    container_name: gitea-runner
    environment:
      CONFIG_FILE: /config.yaml
    volumes:
      - /media/justsave/docker/volume/gitea/runner/config.yaml:/config.yaml
      - /media/justsave/docker/volume/gitea/runner/data:/data
      - /media/justsave/docker/volume/gitea/runner/root:/root
      - /media/justsave/docker:/media/justsave/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
