# version: "3"

# official repo URL=https://github.com/curl/curl-container
services:
  curl_test:
    container_name: curl-test
    image: ghcr.io/curl/curl-container/curl:master
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "curl --head https://www.google.com/"
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: "no"
