# version: "3"

# official docs URL=https://github.com/docker-library/docs/blob/master/nginx/README.md
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    pull_policy: always
    network_mode: host
    restart: always
    volumes:
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # nginx conf file
      - /media/justsave/docker/volume/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # nginx vhost
      - /media/justsave/docker/volume/nginx/conf.d:/etc/nginx/conf.d:ro
      # nginx snippets
      - /media/justsave/docker/volume/nginx/snippets:/etc/nginx/snippets:ro
      # nginx ssl cert
      - /media/justsave/docker/volume/nginx/ssl:/etc/nginx/ssl:ro
      # apache htpasswd file
      - /media/justsave/docker/volume/nginx/htpasswd:/etc/nginx/htpasswd:ro
      # nginx web root
      - /media/justsave/wwwroot:/media/justsave/wwwroot:ro
      # - /media/justsave/wwwroot/default:/var/www/html:ro
      - /media/justsave/BT:/media/justsave/BT:ro
      - /media/justsave/PT:/media/justsave/PT:ro
      - /etc/apt:/etc/apt:ro
      - /usr/share/keyrings:/usr/share/keyrings:ro
      - /media:/media:ro
      # nginx log
      - /media/justsave/wwwlogs:/media/justsave/wwwlogs
      # php-fpm unix socket
      - /var/run/php:/var/run/php
      # mysql unix socket
      - /var/run/mysqld:/var/run/mysqld
      # ttyd unix socket
      - /var/run/ttyd:/var/run/ttyd

