# version: '3'

# official repo URL=https://github.com/nicolargo/glances
services:
  code_server:
    env_file:
      - path: /media/justsave/docker/compose/global_default.env
        required: true
      - path: /media/justsave/docker/env/code_server/docker.env
        required: false
    container_name: code-server
    image: codercom/code-server:latest-xfl
    pull_policy: build
    build:
      context: ./
      dockerfile: code-server-xfl.Dockerfile
    # environment:
    #   - DOCKER_USER="code-server"
    user: "2006:2006"
    volumes:
      # 持久化
      - /media/justsave/docker/volume/code_server/home/.local:/home/coder/.local
      - /media/justsave/docker/volume/code_server/home/.config:/home/coder/.config
      - /media/justsave/docker/volume/code_server/home/project:/home/coder/project
      # # 挂载 docker socket ，直通宿主机
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:28042:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

#mkdir -p ~/.config
#docker run -it --name code-server -p 127.0.0.1:8080:8080 \
#-v "$HOME/.local:/home/coder/.local" \
#-v "$HOME/.config:/home/coder/.config" \
#-v "$PWD:/home/coder/project" \
#-u "$(id -u):$(id -g)" \
#-e "DOCKER_USER=$USER" \
#codercom/code-server:latest