services:
  glances:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: glances
    logging:
      options:
        max-size: 4m
    volumes:
      - /etc/os-release:/etc/os-release:ro
    network_mode: host
