# version: "3"

# source code URL=https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml
services:
  wg_easy:
    env_file: /media/justsave/docker/env/wg_easy/docker.env
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      # - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      # - WG_HOST=raspberrypi.local
      # Optional:
      # - PASSWORD=foobar123
      - PORT=28017
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    pull_policy: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /media/justsave/docker/volume/wg_easy/data/etc/wireguard:/etc/wireguard
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:28017:28017/tcp"
    restart: unless-stopped
