services:
  xfl_cv_javaweb:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: xfl_cv_javaweb
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - 127.0.0.1:28010:8880
