services:
  puter:
    extends:
      file: ./docker-compose.morefree.example.yml
      service: puter
    logging:
      options:
        max-size: 4m
    network_mode: bridge
    ports:
      - 4100:4100
