services:
  netclient:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: netclient

  netmaker:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: netmaker

  netmaker_ui:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: netmaker_ui

  coredns:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: coredns

  mq:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: mq

include:
  - ./docker-compose.cloudflare.network.yml
