services:
  netclient:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: netclient
    logging:
      options:
        max-size: 4m
    network_mode: host
  netmaker:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: netmaker
    logging:
      options:
        max-size: 4m
  netmaker_ui:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: netmaker_ui
    depends_on:
      - netmaker
    logging:
      options:
        max-size: 4m
  coredns:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: coredns
    depends_on:
      - netmaker
    logging:
      options:
        max-size: 4m
  mq:
    extends:
      file: ./docker-compose.cloudflare.example.yml
      service: mq
    depends_on:
      - netmaker
    logging:
      options:
        max-size: 4m
include:
  - ./docker-compose.cloudflare.network.yml
