# version: "3"
services:
  busybox_test:
    container_name: busybox-test
    image: busybox
    network_mode: bridge
    # command: 'sh -c "ifconfig && ping6 -c 4 www.taobao.com"'
    command: /bin/sh -c "touch /tmp/just_hold_docker_bash.txt && tail -f /tmp/just_hold_docker_bash.txt"

# 强行停机方法
# docker compose down --timeout 1
